---
title: "Motor Trend Analysis"
author: "Jeffrey M. Hunter"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: cosmo
    keep_md: no
    df_print: paged
  pdf_document:
    toc: yes
    df_print: paged
    number_sections: false
    fig_caption: yes
    highlight: tango
    dev: pdf
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path='figures/')
```

## Course Project

**Regression Models Course Project**

Peer-graded Assignment

* This course project is available on GitHub

    <a href="https://github.com/oraclejavanet/regression-models-course-project" target="_top">Motor Trend Analysis</a>

## Synopsis


## Environment Setup

Load packages used in this analysis.

```{r load-packages, echo = TRUE}
# load libraries
if (!require("ggplot2")) {
    install.packages("ggplot2")
    library("ggplot2")
}
if (!require("dplyr")) {
    install.packages("dplyr")
    library("dplyr")
}
```

## Load Data



## Exploratory Data Analysis


## Linear Models




## Analysis of Residuals




## Conclusion




